### ISSUE TITLE
Response code 400 (Bad Request) when getting token

### ISSUE THREAD

**Issue by mikecann** [DrewML/chrome-webstore-upload#28]
Hey,

Not sure whats changed but im now getting and error when doing the following:

```
const webStore = require("chrome-webstore-upload")({
    extensionId: stage.extensionId,
    clientId: process.env.CHROME_WEBSTORE_CLIENT_ID,
    clientSecret: process.env.CHROME_WEBSTORE_CLIENT_SECRET,
    refreshToken: process.env.CHROME_WEBSTORE_REFRESH_TOKEN,
  });

  const myZipFile = fs.createReadStream(getZipFilePath(stage.name));

  await webStore.uploadExisting(myZipFile);
```

The error is:

```
{ HTTPError: Response code 400 (Bad Request)
    at stream.catch.then.data (C:\dev\markd\markd-extension\node_modules\got\index.js:123:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  message: 'Response code 400 (Bad Request)',
  host: 'www.googleapis.com',
  hostname: 'www.googleapis.com',
  method: 'POST',
  path: '/oauth2/v4/token',
  statusCode: 400,
  statusMessage: 'Bad Request' }
```

I think its failing when trying to auto-get the token?

**Comment by Narno** [comment]
https://github.com/DrewML/chrome-webstore-upload/search?q=bad+request+is%3Aissue&type=Issues

**Comment by mikecann** [comment]
Ahh sorry I fotgot to search this time for other issues :)
